# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnrKI4PXG-t-_EPJG2Nhdtu5Jefj7u09
"""

import time
import tracemalloc
import sys

# Drastically increase recursion depth to accommodate deep N-Queens search stacks
sys.setrecursionlimit(500000)

def solve_n_queens_dfs(n, timeout_seconds=600):
    tracemalloc.start()
    start_time = time.time()

    solution = []

    def dfs(row, columns, diagonals1, diagonals2, current_state):
        # Time threshold validation check
        if time.time() - start_time > timeout_seconds:
            return "TLE"

        if row == n:
            solution.append(current_state)
            return "SUCCESS"

        for col in range(n):
            if col in columns or (row - col) in diagonals1 or (row + col) in diagonals2:
                continue

            res = dfs(row + 1,
                      columns | {col},
                      diagonals1 | {row - col},
                      diagonals2 | {row + col},
                      current_state + [col])

            if res == "SUCCESS":
                return "SUCCESS"
            elif res == "TLE":
                return "TLE"

        return "FAIL"

    # Initialize the backtracking engine
    status = dfs(0, set(), set(), set(), [])

    end_time = time.time()
    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    latency = end_time - start_time
    peak_kb = peak / 1024

    if status == "SUCCESS":
        return f"Success: Valid configuration isolated!\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"
    elif status == "TLE":
        return f"Timeout: Exceeded {timeout_seconds/60:.1f} minutes!\nExecution Latency: TLE\nPeak Memory Demand: N/A"
    else:
        return "No Solution Found."

# --- RUNNING 10-MINUTE BENCHMARK ENGINE ---
n_values = [10, 30, 50, 100, 200, 500]

for n in n_values:
    print(f"--- Running Depth-First Search (DFS) for N = {n} ---")
    try:
        result = solve_n_queens_dfs(n, timeout_seconds=600) # 10 minutes limit
        print(result)
    except Exception as e:
        print(f"Error encountered: {e}")
    print("\n" + "="*40 + "\n")