# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnrKI4PXG-t-_EPJG2Nhdtu5Jefj7u09
"""

import time
import tracemalloc
import random

def get_fitness(chrom, n):
    """Calculates non-attacking pairs. A perfect board has max_fitness."""
    max_fitness = (n * (n - 1)) // 2
    horizontal_collisions = sum(chrom.count(queen) - 1 for queen in chrom) // 2

    diagonal_collisions = 0
    left_diagonal = [0] * (2 * n)
    right_diagonal = [0] * (2 * n)
    for i in range(n):
        left_diagonal[i + chrom[i]] += 1
        right_diagonal[i - chrom[i] + n - 1] += 1

    for i in range(2 * n):
        if left_diagonal[i] > 1:
            diagonal_collisions += (left_diagonal[i] - 1)
        if right_diagonal[i] > 1:
            diagonal_collisions += (right_diagonal[i] - 1)

    return max_fitness - (horizontal_collisions + diagonal_collisions)

def crossover(parent1, parent2, n):
    """Performs single-point crossover."""
    c = random.randint(0, n - 1)
    return parent1[:c] + parent2[c:]

def mutate(chrom, n):
    """Randomly alters one gene (queen position) with a low probability."""
    c = random.randint(0, n - 1)
    r = random.randint(0, n - 1)
    chrom[c] = r
    return chrom

def solve_n_queens_ga(n, population_size=100, max_generations=2000, timeout_seconds=300):
    tracemalloc.start()
    start_time = time.time()

    max_fitness = (n * (n - 1)) // 2

    # Generate initial population randomly
    population = [[random.randint(0, n - 1) for _ in range(n)] for _ in range(population_size)]
    status = "FAIL"

    for generation in range(max_generations):
        # 5-Minute Timeout Guard
        if time.time() - start_time > timeout_seconds:
            status = "TLE"
            break

        # Calculate fitness for entire population
        population_fitness = [get_fitness(chrom, n) for chrom in population]

        # Check if perfect solution is found
        if max_fitness in population_fitness:
            status = "SUCCESS"
            break

        # Selection using roulette wheel probability weights
        fit_sum = sum(population_fitness)
        if fit_sum == 0:
            weights = [1 / population_size] * population_size
        else:
            weights = [f / fit_sum for f in population_fitness]

        new_population = []
        for _ in range(population_size // 2):
            parent1, parent2 = random.choices(population, weights=weights, k=2)
            child1 = crossover(parent1, parent2, n)
            child2 = crossover(parent2, parent1, n)

            # Apply mutation with a 10% chance
            if random.random() < 0.1: child1 = mutate(child1, n)
            if random.random() < 0.1: child2 = mutate(child2, n)

            new_population.extend([child1, child2])

        population = new_population

    end_time = time.time()
    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    latency = end_time - start_time
    peak_kb = peak / 1024

    if status == "SUCCESS":
        return f"Success: Valid configuration isolated!\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"
    elif status == "TLE":
        return f"Timeout: Exceeded {timeout_seconds/60:.1f} minutes!\nExecution Latency: TLE\nPeak Memory Demand: {peak_kb:.2f} KB"
    else:
        return f"Fail: Max generations reached.\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"

# --- RUNNING GENETIC ALGORITHM BENCHMARK ENGINE ---
n_values = [10, 30, 50, 100, 200, 500]

for n in n_values:
    print(f"--- Running Genetic Algorithm (GA) for N = {n} ---")
    try:
        result = solve_n_queens_ga(n, timeout_seconds=300)
        print(result)
    except Exception as e:
        print(f"Error encountered: {e}")
    print("\n" + "="*40 + "\n")