# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnrKI4PXG-t-_EPJG2Nhdtu5Jefj7u09
"""

import time
import tracemalloc
import random
import math

def get_sa_conflicts(state, n):
    """Calculates the total number of attacking pairs of queens."""
    conflicts = 0
    for i in range(n):
        for j in range(i + 1, n):
            if state[i] == state[j] or abs(state[i] - state[j]) == abs(i - j):
                conflicts += 1
    return conflicts

def solve_n_queens_sa(n, initial_temp=100.0, cooling_rate=0.98, max_steps_per_temp=100, timeout_seconds=300):
    tracemalloc.start()
    start_time = time.time()

    # Initialize state: one queen per column
    state = list(range(n))
    random.shuffle(state)
    current_conflicts = get_sa_conflicts(state, n)

    temperature = initial_temp
    status = "FAIL"

    while temperature > 0.01:
        # Timeout Guard
        if time.time() - start_time > timeout_seconds:
            status = "TLE"
            break

        if current_conflicts == 0:
            status = "SUCCESS"
            break

        for _ in range(max_steps_per_temp):
            if current_conflicts == 0:
                break

            # Pick a random column and a random new row for that column
            col = random.randint(0, n - 1)
            old_row = state[col]
            new_row = random.randint(0, n - 1)

            if old_row == new_row:
                continue

            # Tentatively make the move
            state[col] = new_row
            new_conflicts = get_sa_conflicts(state, n)

            energy_delta = new_conflicts - current_conflicts

            # Simulated Annealing Decision Rule:
            # If the move is better, always accept it.
            # If it's worse, accept it with a probability based on the current Temperature.
            if energy_delta < 0:
                current_conflicts = new_conflicts
            else:
                acceptance_probability = math.exp(-energy_delta / temperature)
                if random.random() < acceptance_probability:
                    current_conflicts = new_conflicts
                else:
                    state[col] = old_row  # Revert the move

        # Cool down the temperature
        temperature *= cooling_rate

    if current_conflicts == 0:
        status = "SUCCESS"

    end_time = time.time()
    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    latency = end_time - start_time
    peak_kb = peak / 1024

    if status == "SUCCESS":
        return f"Success: Valid configuration isolated!\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"
    elif status == "TLE":
        return f"Timeout: Exceeded {timeout_seconds/60:.1f} minutes!\nExecution Latency: TLE\nPeak Memory Demand: {peak_kb:.2f} KB"
    else:
        return f"Fail: Temperature cooled down without resolution.\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"

# --- RUNNING SIMULATED ANNEALING BENCHMARK ENGINE ---
n_values = [10, 30, 50, 100, 200, 500]

for n in n_values:
    print(f"--- Running Simulated Annealing (SA) for N = {n} ---")
    try:
        result = solve_n_queens_sa(n, timeout_seconds=300)
        print(result)
    except Exception as e:
        print(f"Error encountered: {e}")
    print("\n" + "="*40 + "\n")