# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnrKI4PXG-t-_EPJG2Nhdtu5Jefj7u09
"""

import time
import tracemalloc
import random

def get_conflicts(state, n):
    """Calculates the total number of attacking pairs of queens on the board."""
    conflicts = 0
    for i in range(n):
        for j in range(i + 1, n):
            # Check row alignment or diagonal alignment
            if state[i] == state[j] or abs(state[i] - state[j]) == abs(i - j):
                conflicts += 1
    return conflicts

def solve_n_queens_greedy(n, max_steps=5000):
    tracemalloc.start()
    start_time = time.time()

    # Initialize state: one queen per column, placed randomly in rows
    # Using a permutation avoids row/column conflicts, leaving only diagonal conflicts
    state = list(range(n))
    random.shuffle(state)

    current_conflicts = get_conflicts(state, n)
    status = "FAIL"

    for step in range(max_steps):
        if current_conflicts == 0:
            status = "SUCCESS"
            break

        # Select a random column that has conflicts
        col = random.randint(0, n - 1)
        original_row = state[col]
        best_row = original_row
        min_conflicts = current_conflicts

        # Greedy Step: Test every other row in this column to find the absolute minimum conflicts
        for row in range(n):
            if row == original_row:
                continue
            state[col] = row
            new_conflicts = get_conflicts(state, n)

            if new_conflicts < min_conflicts:
                min_conflicts = new_conflicts
                best_row = row

        # If an improvement was found, update the board state
        if best_row != original_row:
            state[col] = best_row
            current_conflicts = min_conflicts
        else:
            # Side-step/random walk if stuck in a local minimum
            state[col] = random.randint(0, n - 1)
            current_conflicts = get_conflicts(state, n)

    if current_conflicts == 0:
        status = "SUCCESS"

    end_time = time.time()
    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    latency = end_time - start_time
    peak_kb = peak / 1024

    if status == "SUCCESS":
        return f"Success: Valid configuration isolated!\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"
    else:
        return f"Fail: Max steps reached without resolution.\nExecution Latency: {latency:.6f} seconds\nPeak Memory Demand: {peak_kb:.2f} KB"

# --- RUNNING GREEDY BENCHMARK ENGINE ---
n_values = [10, 30, 50, 100, 500]

for n in n_values:
    print(f"--- Running Greedy Local Search for N = {n} ---")
    try:
        result = solve_n_queens_greedy(n)
        print(result)
    except Exception as e:
        print(f"Error encountered: {e}")
    print("\n" + "="*40 + "\n")